
nav:
  - Home: index.md
  - CPA Data Analysis:
      - Likelihood: "000 CPA Data Analysis/likelihood.md"

nav:
  - Home: index.md
  - CPA Data Analysis:
      - Likelihood: "000 CPA Data Analysis/likelihood.md"
site_name: sw_portfolio
theme: readthedocs

nav:
  - Home: index.md
  - Likelihood: likelihood.md

markdown_extensions:
  - toc:
      permalink: true
