site_name: Swayer
theme: readthedocs

nav:
  - Home: index.md

  - CPA Data Analysis: "CPA Data Analysis/index.md"
  - 00 This and That: "00 This and That/index.md"
  - 01 Mathematical Statistics: "01 Mathematical Statistics/index.md"
  - 02 ESL: "02 ESL/index.md"
  - 03 Theoretical Statistics: "03 Theoretical Statistics/index.md"
  - 04 Multivariate Statistics: "04 Multivariate Statistics/index.md"
  - 05 Design of Experiments: "05 Design of Experiments/index.md"
  - 06 Simulation Practice and Theory: "06 Simulation Practice and Theory/index.md"
  - 07 Intermediate Applied Statistics: "07 Intermediate Applied Statistics/index.md"
  - 08 Statistical Learning Theory: "08 Statistical Learning Theory/index.md"
  - 09 Graduate Mathematical Statistics: "09 Graduate Mathematical Statistics/index.md"
  - 10 Bayesian Statistics: "10 Bayesian Statistics/index.md"
  - 99 Ybigta ML: "99 Ybigta ML/index.md"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  

plugins:
  - search
  - mkdocs-jupyter:
      execute: true
      include_source: true